language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge

  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n emiprep_test python=$TRAVIS_PYTHON_VERSION --file requirements_dev.txt
  - source activate emiprep_test
  - python setup.py install

script:
  - python setup.py test
  - codecov

after_success:
  # Change permissions for Anaconda deployment script
  - chmod +x ./conda/mk_conda_package.sh

deploy:
  # Deploy to Anaconda.org
  # see https://gist.github.com/yoavram/05a3c04ddcf317a517d5
  - provider: script
    script: ./conda/mk_conda_package.sh
    on:
      branch: master
    skip_cleanup: true
